Revert "try to use Appium github action"
This reverts commit 22451735bf61c467c9d9d92e524dadfc876c64df.

The action failed on github actions:
```
Run moatazeldebsy/Appium-Server-GitHub-Action@V1.0.7
Error: Container action is only supported on Linux
```